### PR TITLE
Add rpm stuff for el7 (tested on centos 7.1)

### PR DESCRIPTION
**Pull request by sheepkiller**
Hi,

Thanks for this awesome plugin.

### CODE REVIEW

**Comment by hekaldama** [comment]
Thanks for contributing! Do you want to take a stab at wrapping these up in the Makefile as well. Maybe even document in the README?

**Comment by sheepkiller** [comment]
No problem. I personnaly use a docker image to build the rpm ( https://github.com/sheepkiller/rbd-docker-plugin-rpm ). Do you prefer a Makefile ?

**Comment by sheepkiller** [comment]
done :)

**Comment by hekaldama** [comment]
Looking at this more fully now.

**Comment by hekaldama** [comment]
Everything seems like it is in order, though I am no rpm expert. What does this give us at the end of the day? The ability to release rpms for this project?

**Comment by sheepkiller** [comment]
Sure, you can release RPM, but the initial goal was to provide a simple way to deploy your plugin with a CM software, without the hassle of handling a custom workflow.

**Pull request merged**
