### PR TITLE
Add getRBDDeviceName function to query rbd show mapped and pull out t…

### PR DESCRIPTION
**Pull request by deanpemberton**
Add getRBDDeviceName function to query rbd show mapped and pull out he mapped device name.

Looks to solve
https://github.com/yp-engineering/rbd-docker-plugin/issues/19

### CODE REVIEW

**Comment by hekaldama** [comment]
How did this go? Did you end up updating ceph?

**Comment by deanpemberton** [comment]
I haven't. I'll let you know when I cycle back past this problem

On Wednesday, 10 February 2016, Adam Avilla notifications@github.com
wrote:

> How did this go? Did you end up updating ceph?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yp-engineering/rbd-docker-plugin/pull/20#issuecomment-182188779
> .

## 

Regards,

Dean

**Comment by hekaldama** [comment]
@deanpemberton should I close this one? Did you find a solution for yourself? Did you find a way to make it helpful for all? Thanks.

**Comment by deanpemberton** [comment]
Please close.

We ended up going in another direction

On Friday, 18 March 2016, Adam Avilla notifications@github.com wrote:

> @deanpemberton https://github.com/deanpemberton should I close this
> one? Did you find a solution for yourself? Did you find a way to make it
> helpful for all? Thanks.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/yp-engineering/rbd-docker-plugin/pull/20#issuecomment-198114803

## 

Regards,

Dean

**Pull request closed without merging**
